//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaAvaliacao
    {
        public int idFichaAvaliacao { get; set; }
        public Nullable<int> idInscricaoTurma { get; set; }
        public Nullable<int> idAvaliacaoTutoria { get; set; }
        public Nullable<decimal> nota { get; set; }
    
        public virtual AvaliacaoTutoria AvaliacaoTutoria { get; set; }
    }
}
