//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public int idGrupo { get; set; }
        public Nullable<int> idProfessor { get; set; }
        public string descGrupo { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
