//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prova
    {
        public int idProva { get; set; }
        public Nullable<int> idTipoProva { get; set; }
        public Nullable<decimal> valorQuestao { get; set; }
    
        public virtual TipoProva TipoProva { get; set; }
    }
}
